// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billing_account_event.proto

// Protobuf Java Version: 3.25.5
package billing.events;

public final class BillingAccountEventOuterClass {
  private BillingAccountEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_billing_events_BillingAccountEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_billing_events_BillingAccountEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033billing_account_event.proto\022\016billing.e" +
      "vents\"Y\n\023BillingAccountEvent\022\021\n\tpatientI" +
      "d\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\022\n\n" +
      "event_type\030\004 \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_billing_events_BillingAccountEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_billing_events_BillingAccountEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_billing_events_BillingAccountEvent_descriptor,
        new java.lang.String[] { "PatientId", "Name", "Email", "EventType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
